apiVersion: v1
kind: Pod
metadata:
  labels:
    run: volume-pod
  name: volume-pod
  namespace: dev
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Success > /output/success.txt']
    volumeMounts:
    - name: my-volume
      mountPath: /output
  restartPolicy: Never
  volumes:
    - name: my-volume
      hostPath:
        path: /var/data
status: {}
