apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-dnstest
  name: busybox-dnstest
  namespace: dev
spec:
  containers:
  - name: busybox-dnstest
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-dnstest
  name: nginx-dnstest
  namespace: dev
spec:
  containers:
  - name: nginx-dnstest
    image: nginx
    ports:
      - containerPort: 80
