apiVersion: v1
kind: Pod
metadata:
  name: always-restart-pod
  labels:
    name: always-restart-pod
  namespace: dev
spec:
  restartPolicy: Always # No need to provide this in yaml since this is the default
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 10']
