apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    name: init-pod
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx
  initContainers:
    - name: delay
      image: busybox
      command: ["sleep", "3000"]
