apiVersion: v1
kind: Pod
metadata:
  name: onfailure-restart-pod
  labels:
    name: onfailure-restart-pod
  namespace: dev
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 10']
