apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  labels:
    name: sidecar-pod
  namespace: dev
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - while true; do echo logs data > /output/output.log; sleep 5; done
    volumeMounts:
      - name: shared-volume
        mountPath: /output  
  - name: sidecar
    image: busybox
    command:
      - sh
      - -c
      - tail -f /input/output.log
    volumeMounts:
      - name: shared-volume
        mountPath: /input
  volumes:
    - name: shared-volume
      emptyDir: {}