apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-http
  labels:
    app: liveness-pod-http
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:latest
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 10